### ISSUE TITLE
banner ad not work

### ISSUE THREAD

**Issue by hortigado** [dnaextrim/flutter_ironsource_x#12]
hi. the banner ad work? i implement it but the banner not displayed

**Comment by hortigado** [comment]
I already solved it, you have to wait for the await IronSource.initialize to finish and you have to show the banner

**Comment by Loukili-Rachid** [comment]
@hortigado  could please share an example I have the same prblm. I will be very thankful

**Comment by hortigado** [comment]
`void onInit() async {    
super.onInit();
    var userId = await IronSource.getAdvertiserId();
    await IronSource.validateIntegration();
    await IronSource.setUserId(userId);
    await IronSource.initialize(appKey: appKey, gdprConsent: true);

    bannerAd = IronSourceBannerAd(
      keepAlive: true,
      listener: BannerAdListener(),
      size: BannerSize.BANNER,
    );
    update();
}`

**Comment by Loukili-Rachid** [comment]
@hortigado many thank first , i tried but without succeed , i'm using getx i cant figure out how to handle your code with it
