### ISSUE TITLE
Having error related to Kotlin version

### ISSUE THREAD

**Issue by Neo490** [dnaextrim/flutter_ironsource_x#17]
Hello :) many thanks for creating this plugin~

The provided repo works fine in terms of getting the build done, but I'm having this error when trying to build on personal projects:

---

Running Gradle task 'assembleDebug'...
e: C:/Users/myname/.gradle/caches/transforms-2/files-2.1/683fded33b117c0eb9bb9deabca1a71e/work-runtime-2.7.0-api.jar!/META-INF/work-runtime_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.15.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_ironsource_x:compileDebugKotlin'.
> Compilation error. See log for more details

---

I wonder if I could just copy the .kt file found inside example repo's "app/src/main/kotlin.../MainActivity.kt", but I really don't know..

Could you kindly help me out?

My build.gradle's dependencies is as follows. As I wasn't sure which ones I need (or will need in near future, like the multidex and appcompat, from the repo):

---

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.gms:play-services-ads-identifier:17.0.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.ironsource.sdk:mediationsdk:7.1.14'
}

---

Also, do I need the AdMob-related metadata in my AndroidManifest.xml,?:

---
meta-data
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="ca-app-pub-3940256099942544~3347511713"
---

Kind regards, thank you for any guidance

**Comment by dnaextrim** [comment]
You can change Kotlin version like this, in path: [root_project]/android/build.gradle
![image](https://user-images.githubusercontent.com/390712/152117332-9625b9a5-17e5-410e-a08a-2c0f23eb9ec7.png)

**Comment by Neo490** [comment]
Im a little confused regarding my setup. I did not have a buildscript section by default.
Is it okay to write these versions as so? I assume I should use a different version for the gradle (second underline)? 
And regarding the error, I should probably download the kotlin version from kotlin's site to my disk and load it probably..

![Screenshot_4](https://user-images.githubusercontent.com/96939312/152162111-3af7e1a5-d3a3-4d2b-b48e-8f397fe046f2.png)

**Comment by dnaextrim** [comment]
for this problem I just change the Kotlin version like this 'ext.kotlin_version = '1.4.21'', after I change then I run again, and the problem is solved.

maybe you can show all your [root_project]/android/build.gradle code generated by flutter project here
