### ISSUE TITLE
Unity sdk non complaint warning from playstore

### ISSUE THREAD

**Issue by 92sajid110** [dnaextrim/flutter_ironsource_x#23]
Your app includes SDK com.unity3d.ads:unity-ads or an SDK that one of your libraries depends on, which collects personal or sensitive data that includes but may not be limited to Advertising ID, Android ID identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers

According to the information provided by your SDK provider, you may consider upgrading to 4.0.1. Please consult the SDK provider for further information.

**Comment by 92sajid110** [comment]
any update on this?

**Comment by bayramaliunuvar** [comment]
new update has arrived
