### ISSUE TITLE
init() had failed

### ISSUE THREAD

**Issue by elkhalifte** [dnaextrim/flutter_ironsource_x#6]
i have the integration worked perfectly.
but ads wont load and showing the error 508.

i think the problem is the ad must init in the initialize methode 
like this in the ironsource docs : 

`IronSource.init(this, appKey, IronSource.AD_UNIT.OFFERWALL, IronSource.AD_UNIT.INTERSTITIAL, IronSource.AD_UNIT.REWARDED_VIDEO, IronSource.AD_UNIT.BANNER);`

**Comment by dnaextrim** [comment]
I'm still looking for the cause of the problem because the ads sometimes appear and sometimes they don't. In this picture is a picture of the results of the implementation in my project
![image](https://user-images.githubusercontent.com/390712/132304579-25536cd8-abba-448a-be06-c65640550db4.png)

**Comment by elkhalifte** [comment]
Please try my suggestion

**Comment by dnaextrim** [comment]
Ok. Thanks for your suggestion, I will try it
